
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://eflkehzzvaumatnapmrm.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbGtlaHp6dmF1bWF0bmFwbXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzU2ODAsImV4cCI6MjA2MzAxMTY4MH0.1YS6MStH0QzQbcr4r2uas1ZOOSnpwoGbdlkFVrl3ceM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
